### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by Johnabarreto** [MicrosoftDocs/quantum-docs-pr.es-ES#1]
This page have something errors in the translation to Spanish for example:

- cómo se puede ver un equipo Quantum como 

Correct is: como se puede ver en un equipo cuantico

- usar las puertas de Quantum para rotar

Correct: usar las puertas cuanticas para rotar

-Esta parte no se entiende: realice una calcul bicación.

In general, the principal error is the  bad translation in Quantum, in Spanish es cuantico or cuantica 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 01d6a756-87d7-9dae-705a-ab112ba272a9
* Version Independent ID: 5042a750-09e9-8de5-f785-bf40d929829b
* Content: [Recursos de aprendizaje de Quantum Computing - Microsoft Quantum](https://docs.microsoft.com/es-es/quantum/for-more-info?view=qsharp-preview#feedback)
* Content Source: [articles/for-more-info.md](https://github.com/MicrosoftDocs/quantum-docs-pr.es-ES/blob/live-sxs/articles/for-more-info.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @Johnabarreto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hola, @Johnabarreto:

Gracias por su contribución. 

Actualmente no se aceptan aportaciones relacionadas con problemas de traducción para el contenido de traducción automática. 

Le agradecemos sus comentarios y sugerencias sobre el contenido traducido por personas, que se usa para entrenar los motores de traducción automática, por lo que, con el tiempo, sus contribuciones mejorarán la calidad tanto de la traducción automática como de la traducción humana. 

Los temas traducidos por personas pueden distinguirse de los temas traducidos de forma automática por el valor “HT” de ms.translationtype en los metadatos (frente a “MT” para la traducción automática) en el encabezado de cada archivo de contenido. 

Muchas gracias por su ayuda. 

Equipo de experiencia global de Microsoft DOCS

**Comment by Johnabarreto** [comment]
Hola Tatiana, muchas gracias por tu respuesta, adicional a esto el tema de los ejemplos que no se logran ver de forma adecuada, van ligado a la traducción automática?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ticianaciminari** [comment]
@Johnabarreto, reactivaremos este ticket: https://github.com/MicrosoftDocs/quantum-docs-pr.es-ES/issues/2 y lo enviaremos al repositorio source para que solucionen este problema.

Atentamente,  

Equipo internacional de Microsoft Docs

**Comment by Johnabarreto** [comment]
Hola Ticiana,

Genial, voy a seguir revisando la documentación y comentando lo que pueda tener puntos de mejora!!!

You are the best!!!

Sent from my iPhone

On 28/01/2020, at 2:35 PM, Ticiana Ciminari <notifications@github.com> wrote:

﻿

@Johnabarreto<https://github.com/Johnabarreto>, reactivaremos este ticket: #2<https://github.com/MicrosoftDocs/quantum-docs-pr.es-ES/issues/2> y lo enviaremos al repositorio source para que solucionen este problema.

Atentamente,

Equipo internacional de Microsoft Docs
