### ISSUE TITLE
Translation error and problem for show the matemathical examples 

### ISSUE THREAD

**Issue by Johnabarreto** [MicrosoftDocs/quantum-docs-pr.es-ES#2]
The document have something error in the translation to Spanish, for example Dimension (o size) this is Dimension (o tamaño).

Additional in the mathematical examples no working fine,  show this information:  \begin{align} & \begin{bmatrix} 1 \\ 0 \end{bmatrix} ^ {\otimes 1} = \begin{bmatrix} 1 

In English working fine!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectores y matrices - Microsoft Quantum](https://docs.microsoft.com/es-es/quantum/concepts/vectors-and-matrices?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr.es-ES/blob/live-sxs/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @Johnabarreto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hola, @Johnabarreto:

Gracias por su contribución. 

Actualmente no se aceptan aportaciones relacionadas con problemas de traducción para el contenido de traducción automática. 

Le agradecemos sus comentarios y sugerencias sobre el contenido traducido por personas, que se usa para entrenar los motores de traducción automática, por lo que, con el tiempo, sus contribuciones mejorarán la calidad tanto de la traducción automática como de la traducción humana. 

Los temas traducidos por personas pueden distinguirse de los temas traducidos de forma automática por el valor “HT” de ms.translationtype en los metadatos (frente a “MT” para la traducción automática) en el encabezado de cada archivo de contenido. 

Muchas gracias por su ayuda. 

Equipo de experiencia global de Microsoft DOCS

**Comment by ticianaciminari** [comment]
Hola, @Johnabarreto:

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/quantum-docs-pr/issues/669  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  

Equipo internacional de Microsoft Docs
